module.exports = [
  { letter: 'A', name: 'альфа' },
  { letter: 'B', name: 'бета' },
  { letter: 'Г', name: 'гамма' },
  { letter: 'Δ', name: 'дельта' },
  { letter: 'E', name: 'эпсилон' },
  { letter: 'Z', name: 'дзета' },
  { letter: 'H', name: 'эта' },
  { letter: 'Θ', name: 'тета' },
  { letter: 'I', name: 'йота' },
  { letter: 'K', name: 'каппа' },
  { letter: 'Λ', name: 'лямбда' },
  { letter: 'M', name: 'мю' },
  { letter: 'N', name: 'ню' },
  { letter: 'Ξ', name: 'кси' },
  { letter: 'O', name: 'омикрон' },
  { letter: 'П', name: 'пи' },
  { letter: 'P', name: 'ро' },
  { letter: 'Σ', name: 'сигма' },
  { letter: 'T', name: 'тау' },
  { letter: 'Υ', name: 'ипсилон' },
  { letter: 'Ф', name: 'фи' },
  { letter: 'Х', name: 'хи' },
  { letter: 'Ψ', name: 'пси' },
  { letter: 'Ω', name: 'омега' },
];
